### ISSUE TITLE
Handle touch screen

### ISSUE THREAD

**Issue by ubx** [ubx/meta-glide#5]

**Comment by maluethi** [comment]
Maybe changing [this](https://github.com/ubx/meta-glide/blob/6a2de976b2a90b819bd3b1825dfb19b2e9647e9f/oe-core/layers/meta-glide/recipes-kernel/linux/linux-toradex/0001-displayl.patch#L207) line to GPIO19 (LED.GREEN) would help?

**Comment by maluethi** [comment]
And these [lines](http://git.toradex.com/cgit/linux-toradex.git/tree/arch/arm/mach-tegra/board-colibri_t30.c?h=Colibri-T30_LXDE-Image_2.8b7.-20200610&id=5e3cb65b1b4bff69d925e3c9d4871de9fc9fe38a#n645) also look interesting...

**Comment by ubx** [comment]
Implemented.
